#!/usr/bin/env bash
# Shebang for better file detection

# Declare Variables before exporting.
# See https://www.shellcheck.net/wiki/SC2155

# Base User
BASE_ADD_USER="yes"
BASE_USER="pi"
BASE_USER_PASSWORD="yumi"

# Needed while building for non rpi sbc
BASE_DISTRO="armbian"
BASE_IMAGE_RASPBIAN="no"

# partition resizing
BASE_ROOT_PARTITION="2"
BASE_IMAGE_ENLARGEROOT=4000
BASE_IMAGE_RESIZEROOT=2600
# Set boot partition mountpoint
BASE_BOOT_MOUNT_PATH="/boot/"
# Compress not needed due compression done in workflow
BASE_RELEASE_COMPRESS=no
# Default module chain
MODULES="base(udev_fix,armbian(armbian_net,omv))"

# export Variables
export BASE_ADD_USER
export BASE_USER
export BASE_USER_PASSWORD
export BASE_DISTRO
export BASE_IMAGE_RASPBIAN
export BASE_ROOT_PARTITION
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export BASE_BOOT_MOUNT_PATH
export BASE_RELEASE_COMPRESS
export MODULES
